{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gogin.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gogin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.host.goginDomain | quote }}
      secretName: {{ include "gogin.fullname" . }}-cert
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host.goginDomain | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  {{ include "gogin.fullname" . }}
            port:
              number: {{ $svcPort }}
{{- end }}
