apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gogin.fullname" . }}-conf
  labels:
    {{- include "gogin.labels" . | nindent 4 }}
type: "generic"
stringData:
  config.yaml: |
  {{- with .Values.appConfig }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- if .Values.image.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.registry.secret }}
type: kubernetes.io/dockerconfigjson
data:
   .dockerconfigjson: {{ .Values.image.registry.dockerConfig }}
{{- end }}
---
{{- if .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gogin.fullname" . }}-cert
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.goginDomainCert |  b64enc }}
  tls.key:  {{ .Values.ingress.tls.goginDomainKey |  b64enc }}
{{ end }}
