apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gogin.fullname" . }}
  labels:
    {{- include "gogin.labels" . | nindent 4 }}
type: "generic"
stringData:
  config.yaml: |
    {{- with .Values.appConfig.auth }}
    auth:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    port: {{ .Values.appConfig.port }}
    log_level: {{ .Values.appConfig.log_level }}
---
{{- if .Values.image.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.registry.secret }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.registry.dockerconfigjson }}
{{- end }}
---
{{- if .Values.ingress.tls }}
apiVersion: v1
data:
  tls.crt: {{ .Values.ingress.tls.goginDomainCert |  b64enc }}
  tls.key:  {{ .Values.ingress.tls.goginDomainKey |  b64enc }}
kind: Secret
metadata:
  name: {{ include "gogin.fullname" . }}-cert
type: kubernetes.io/tls
{{ end }}
