apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gogin.serviceAccountName" . }}
  labels:
    {{- include "gogin.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}