apiVersion: v1
kind: Service
metadata:
  name: {{ include "gogoin.fullname" . }}
  labels:
    {{- include "gogoin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.appConfig.port }}
      protocol: TCP
  selector:
    {{- include "gogin.selectorLabels" . | nindent 4 }}
