apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gogin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gogin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gogin.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ include "gogin.fullname" . }}
      labels:
        {{- include "gogin.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: {{ include .Values.registry.secret }}
      containers:
      - name: {{ include "gogin.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /v1/info
            port: 8080
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/info
            port: 8080
          initialDelaySeconds: 10
