apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gogin-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: gogin-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
  - http:
      paths:
      - path: /gogin(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: gogin
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress
spec:
  selector:
    name: gogin-ingress
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443