apiVersion: v1
kind: Service
metadata:
  name: {{ include "gogin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gogin.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080
  selector:
    {{- include "gogin.selectorLabels" . | nindent 4 }}